# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.students_pb2 as students__pb2

class StudentOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchStudents = channel.unary_unary(
                '/main.StudentOperations/FetchStudents',
                request_serializer=students__pb2.FetchStudentsRequest.SerializeToString,
                response_deserializer=students__pb2.StudentsResponse.FromString,
                )
        self.CreateStudent = channel.unary_unary(
                '/main.StudentOperations/CreateStudent',
                request_serializer=students__pb2.CreateStudentRequest.SerializeToString,
                response_deserializer=students__pb2.StudentsResponse.FromString,
                )
        self.UpdateStudent = channel.unary_unary(
                '/main.StudentOperations/UpdateStudent',
                request_serializer=students__pb2.UpdateStudentRequest.SerializeToString,
                response_deserializer=students__pb2.StudentsResponse.FromString,
                )
        self.DeleteStudent = channel.unary_unary(
                '/main.StudentOperations/DeleteStudent',
                request_serializer=students__pb2.DeleteStudentRequest.SerializeToString,
                response_deserializer=students__pb2.StudentsResponse.FromString,
                )


class StudentOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchStudents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStudent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchStudents': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchStudents,
                    request_deserializer=students__pb2.FetchStudentsRequest.FromString,
                    response_serializer=students__pb2.StudentsResponse.SerializeToString,
            ),
            'CreateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStudent,
                    request_deserializer=students__pb2.CreateStudentRequest.FromString,
                    response_serializer=students__pb2.StudentsResponse.SerializeToString,
            ),
            'UpdateStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStudent,
                    request_deserializer=students__pb2.UpdateStudentRequest.FromString,
                    response_serializer=students__pb2.StudentsResponse.SerializeToString,
            ),
            'DeleteStudent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStudent,
                    request_deserializer=students__pb2.DeleteStudentRequest.FromString,
                    response_serializer=students__pb2.StudentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.StudentOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchStudents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.StudentOperations/FetchStudents',
            students__pb2.FetchStudentsRequest.SerializeToString,
            students__pb2.StudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.StudentOperations/CreateStudent',
            students__pb2.CreateStudentRequest.SerializeToString,
            students__pb2.StudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.StudentOperations/UpdateStudent',
            students__pb2.UpdateStudentRequest.SerializeToString,
            students__pb2.StudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteStudent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.StudentOperations/DeleteStudent',
            students__pb2.DeleteStudentRequest.SerializeToString,
            students__pb2.StudentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
