# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: students.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estudents.proto\x12\x04main\"0\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"B\n\x14\x46\x65tchStudentsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0f\n\x07perPage\x18\x03 \x01(\x05\"1\n\x14\x43reateStudentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"=\n\x14UpdateStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\"\n\x14\x44\x65leteStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"T\n\x10StudentsResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\x08students\x18\x03 \x03(\x0b\x32\r.main.Student2\xaf\x02\n\x11StudentOperations\x12\x45\n\rFetchStudents\x12\x1a.main.FetchStudentsRequest\x1a\x16.main.StudentsResponse\"\x00\x12\x45\n\rCreateStudent\x12\x1a.main.CreateStudentRequest\x1a\x16.main.StudentsResponse\"\x00\x12\x45\n\rUpdateStudent\x12\x1a.main.UpdateStudentRequest\x1a\x16.main.StudentsResponse\"\x00\x12\x45\n\rDeleteStudent\x12\x1a.main.DeleteStudentRequest\x1a\x16.main.StudentsResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'students_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_STUDENT']._serialized_start=24
  _globals['_STUDENT']._serialized_end=72
  _globals['_FETCHSTUDENTSREQUEST']._serialized_start=74
  _globals['_FETCHSTUDENTSREQUEST']._serialized_end=140
  _globals['_CREATESTUDENTREQUEST']._serialized_start=142
  _globals['_CREATESTUDENTREQUEST']._serialized_end=191
  _globals['_UPDATESTUDENTREQUEST']._serialized_start=193
  _globals['_UPDATESTUDENTREQUEST']._serialized_end=254
  _globals['_DELETESTUDENTREQUEST']._serialized_start=256
  _globals['_DELETESTUDENTREQUEST']._serialized_end=290
  _globals['_STUDENTSRESPONSE']._serialized_start=292
  _globals['_STUDENTSRESPONSE']._serialized_end=376
  _globals['_STUDENTOPERATIONS']._serialized_start=379
  _globals['_STUDENTOPERATIONS']._serialized_end=682
# @@protoc_insertion_point(module_scope)
